language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.local

sudo: enabled

before_install:
  - sudo apt-get update
  - sudo pip install --user awscli
  - sudo export PATH=$PATH:$HOME/.local/bin
  - sudo aws s3 cp s3://steve-jars/ojdbc7.jar .
  - sudo mvn install:install-file -Dfile="ojdbc7.jar" -DgroupId="com.oracle" -DartifactId="ojdbc7" -Dversion="12.1.0" -Dpackaging="jar"

build:
  commands:
    - mvn clean package
deploy:
  provider: opsworks
  access-key-id: AKIAJLEBPPJAKHCJ4RPQ
  secret-access-key: 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
  app-id: eaec693a-73fd-45f8-9495-0712410ca680
  region: us-east-1

artifacts:
  files:
    - target/ERS.war
  discard-paths: yes