language: java
jdk: oraclejdk8

sudo: false

phases:
  run:
    commands:
      - mvn test

  build:
    commands:
      - mvn clean package
  deploy:
    provider: opsworks
    access-key-id: AKIAJLEBPPJAKHCJ4RPQ
    secret-access-key: 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
    app-id: eaec693a-73fd-45f8-9495-0712410ca680
    region: us-east-1

artifacts:
  files:
    - target/java-demo.war
  discard-paths: yes