language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.local
  - $HOME/.m2

sudo: enabled

before_install:
  - pip install --user awscli
  - eval $(aws ecr get-login --region AWS_DEFAULT_REGION)
  
install:
  - sudo wget https://s3.amazonaws.com/steve-jars/ojdbc7.jar
  - eval mvn install:install-file -Dfile="ojdbc7.jar" -DgroupId="com.oracle" -DartifactId="ojdbc7" -Dversion="12.1.0" -Dpackaging="jar"
  
script:
  - mvn clean package
  # - cd target
  # - zip -r ERS ERS ERS.war

deploy:
  # provider: s3
  # # local-dir: target
  # access-key-id: $AWS_ACCESS_KEY_ID
  # secret-access-key: $AWS_SECRET_ACCESS_KEY
  # bucket: team-travis-prod-1337
  # # key: ers.zip
  # # bundle-type: zip
  # # app-id: 14bde92d-b5cb-4590-824b-700d0f570b06
  # # region: us-east-1
  # skip_cleanup: true

  # provider: codedeploy
  # access_key_id: $AWS_ACCESS_KEY_ID
  # secret_access_key: $AWS_SECRET_ACCESS_KEY
  # bucket: team-travis-prod-1337
  # key: target/ERS.war
  # application: ERS
  # deployment_group: ERS-prod
  # skip_cleanup: true

  provider: opsworks
  access-key-id: $AWS_ACCESS_KEY_ID
  secret-access-key: $AWS_SECRET_ACCESS_KEY
  app-id: 14bde92d-b5cb-4590-824b-700d0f570b06
  region: us-east-1
  skip_cleanup: true