language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.local
  - $HOME/.m2

sudo: enabled

before_install:
  - pip install --user awscli
  - eval $(aws ecr get-login --region AWS_DEFAULT_REGION)
  
install:
  - sudo wget https://s3.amazonaws.com/steve-jars/ojdbc7.jar
  - eval mvn install:install-file -Dfile="ojdbc7.jar" -DgroupId="com.oracle" -DartifactId="ojdbc7" -Dversion="12.1.0" -Dpackaging="jar"
  
script:
  - mvn clean package

deploy:
  provider: opsworks
  access-key-id: $AWS_ACCESS_KEY_ID
  secret-access-key: $AWS_SECRET_ACCESS_KEY
  app-id: eaec693a-73fd-45f8-9495-0712410ca680
  region: us-east-1
  skip_cleanup: true